//넘버링 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:sectnums:
//자동 줄바꿈 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:hardbreaks:

:example-caption!:
:example-number!:
//==== block 앞 글자(example) + 숫자 (1.) 없애기
:figure-caption!:


[preface]
== 제품 구입 감사 안내문

(주)오토닉스 제품을 구입해 주셔서 감사합니다.
반드시 사용 전 **안전을 위한 주의 사항**을 완전히 읽고 지키십시오.
본 매뉴얼은 제품에 대한 안내와 바른 사용 방법에 대한 내용을 담고 있으므로 사용자가 쉽게 찾아 볼 수 있는 장소에 보관하십시오.


[preface]
== 매뉴얼 안내

- 매뉴얼의 내용을 충분히 숙지한 후에 제품을 사용하십시오.
- 매뉴얼은 제품 기능에 대해 자세하게 설명한 것으로, 매뉴얼 이외의 내용에 대해서는 보증하지 않습니다.
- 매뉴얼의 일부 또는 전부를 무단으로 편집 또는 복사하여 사용할 수 없습니다.
- 매뉴얼은 제품과 함께 제공하지 않습니다.
  당사 홈페이지 (www.autonics.com) 에서 다운로드하여 사용하십시오.
- 매뉴얼의 내용은 해당 제품의 성능 개선에 따라 사전 예고없이 변경될 수 있으며, 업그레이드 공지는 당사 홈페이지를 통해 제공해 드립니다.
- 버전에 따라 표시가 다소 상이할 수 있습니다.
- 당사에서는 매뉴얼의 내용을 조금 더 쉽게, 정확하게 작성하고자 많은 노력을 기울였습니다. 그럼에도 불구하고 수정해야 될 부분이나 질문사항이 있으시면 당사 홈페이지를 통하여 의견을 주시기 바랍니다.



[preface]
== 매뉴얼의 공통 기호

[WARNING]
====
지시사항을 위반하였을 때, 심각한 상해나 사망이 발생할 가능성이 있는 경우
====

[CAUTION]
====
지시사항을 위반하였을 때, 경미한 상해나 제품 손상이 발생할 가능성이 있는 경우
====

[NOTE]
====
해당 기능에 대한 보충 설명
====

[TIP]
====
해당 기능에 대한 예시
====

[IMPORTANT]
====
해당 기능에 대한 중요 내용
====

<<<


[preface]
== 안전을 위한 주의 사항


// 안전을 위한 주의 사항 시작

USB 사용 시 안전을 위한 주의사항입니다.
‘안전을 위한 주의 사항’은 제품을 안전하고 올바르게 사용하여 사고나 위험을 미리 막기 위한 것이므로 반드시 지키십시오.



[decrete]
=== image:images\warning.svg[Warning, , 30pt] 경고

. 가연성 / 폭발성 / 부식성 가스, 다습, 직사광선, 복사열, 진동, 충격, 염분이 있는 환경에서 사용하지 마십시오.
폭발 및 화재 위험이 있습니다.
. 임의로 제품을 개조하지 마십시오.
화재 위험이 있습니다.




[decrete]
=== image:images\Caution.svg[Caution, 30pt] 주의

. 정격/성능 범위 내에서 사용하십시오.
화재 및 제품 고장 위험이 있습니다.
. 청소 시 마른 수건으로 닦으시고, 물, 유기용제를 사용하지 마십시오.
화재 위험이 있습니다.




[decrete]
=== image:images\Important.svg[Important, 30pt] 취급시 주의 사항

. 취급 시 주의사항에 명기된 사항을 지키십시오. 그렇지 않을 경우, 예기치 못한 사고가 일어날 수 있습니다.
. 불량 USB 포트에 연결하지 마십시오. 저장 장치가 손상되거나 정상 인식되지 않을 수 있습니다.
. 다수의 USB 장비를 함께 사용하는 경우, 인식하지 않거나 오류 등이 발생할 수도 있습니다
. USB 연결 해제 시 안전하게 제거하십시오.
. 장기간 USB 미사용 시 PC에서 제거하여 보관하십시오.
. 분실 또는 도난에 주의하십시오.
. USB에 저장되어있는 데이터를 임의로 삭제하거나 수정하지 마십시오.



본 사용자 매뉴얼에 기재된 사양 등은 제품의 개선을 위하여 예고 없이 변경될 수 있습니다.
반드시 취급설명서, 매뉴얼, 기술해설 (카탈로그, 홈페이지) 의 주의 사항을 지키십시오.

//안전을 위한 주의 사항 끝



<<<


// 라이선스 시작

[preface]
== Autonics 최종 사용자 소프트웨어 라이선스 약관

중요 - "SCADAMaster"(이하 "소프트웨어")를 개봉, 복사, 설치, 또는 사용하기 전에 읽으십시오. 본 약관은 소유권을 증명하지 않습니다. 사용 허가에 관련된 라이선스 약관입니다.
다음의 계약 조건과 규정을 상세히 읽기 전에는 본 소프트웨어와 그에 관련된 어떠한 부분(총체적으로, "소프트웨어"라고 함)이라도 개봉, 사용하거나 로드하지 마십시오. 본 소프트웨어를 로드하거나 사용함으로써, 사용자는 이 계약서의 규약에 동의합니다. 만일 본 계약서의 내용에 동의하지 않으시면, 본 소프트웨어를 개봉, 복사, 설치하거나 사용하지 마십시오.

1. 본 계약서에서 제공된 경우를 제외하고, 사용자는 본 소프트웨어의 어떠한 부분이라도 복사, 수정, 임대, 판매, 배포 또는 양도를 할 수 없으며, 본 소프트웨어의 허가 받지 않은 복사를 방지할 것을 동의합니다.
2. 본 소프트웨어를 역(逆) 엔지니어링, 역(逆) 컴파일, 또는 해체할 수 없습니다.
3. 본 소프트웨어는 소프트웨어 사용권 증서에 명시된 사용자와 정품 Key-Lock을 소유한 클라이언트 컴퓨터에 설치가 가능하며, 초과 설치 사용은 별도의 사용자 Key-Lock을 추가 구매해야 합니다.
4. 본 소프트웨어는, 제 3자 공급자의 소프트웨어나 다른 재산을 포함하고 있을 수도 있으며, 그 중 일부는 함께 들어있는 "license.txt" 파일이나 다른 문서 또는 파일에 의거하여 라이선스되고 확인될 수 있습니다.

**소프트웨어와 저작권의 소유권.**
본 소프트웨어의 모든 복사본의 소유권은 오토닉스 또는 오토닉스의 공급자가 가지게 됩니다. 본 소프트웨어는 대한민국과 다른 나라들의 법률, 그리고 국제 조약의 규정에 의하여 저작권이 부여되고 보호됩니다. 본 소프트웨어로부터 저작권에 대한 어떠한 통고도 삭제하여서는 안됩니다. 오토닉스는 본 소프트웨어와 그 내부에 조회된 제품들을 아무 때나 통보 없이, 그리고 본 소프트웨어를 업데이트 하거나 지원해야 할 의무를 지는 일 없이 바꿀 수 있습니다. 별도로 명시적으로 제시된 경우를 제외하고, 오토닉스는 오토닉스의 특허, 지적 소유권, 등록 상표, 또는 다른 지적 재산권에 관하여 명백한 또는 암시된 어떠한 권리도 부여하지 않습니다. 사용자는 그 수령자가 이러한 규정을 완전히 준수할 것을 동의하고 사용자가 본 소프트웨어의 복사본을 간직하지 않는 경우에만 본 소프트웨어를 양도할 수 있습니다. 양도 시 소프트웨어의 전체를 교부하여야 하며, 양수인이 모든 조건을 동의하여야 합니다. 위반 시 책임은 양도인에게 있으며 오토닉스나 오토닉스의 공급자는 어떠한 보증이나 책임을 지지 않습니다. 

**매체에 대한 제한적 보증.**
본 소프트웨어가 오토닉스에 의하여 물리적인 저장 매체를 사용하여 제공된 경우, 오토닉스는 그 매체가 오토닉스에 의하여 제공된 후로부터 90일 동안 물질적, 물리적인 결함이 없을 것을 보증합니다. 만일 그러한 결함이 발견되었을 경우, 교환을 받거나 오토닉스가 지정할 수 있는 다른 방법으로 본 소프트웨어를 제공받을 수 있도록 그 매체를 오토닉스에 반납하시기 바랍니다.

**기타 보증의 제외.**
상기에서 제시된 경우를 제외하고, 본 소프트웨어는 상거래 보증, 법률 위반의 여부, 또는 특정 용도에의적합성에 대한 보증을 포함하여 어떠한 명시적 또는 묵시적인 보증이 없이 "있는 그대로" 제공됩니다. 오토닉스는 본 소프트웨어에 포함되어 있는 어떠한 정보나 문서 내용, 그래픽, 링크, 또는 기타 다른 사항들의 정확도나 완성도에 대해 보증을 하거나 책임을 지지 않습니다.

**책임의 제한.** 
오토닉스나 오토닉스의 공급자는 어떠한 경우에도 본 소프트웨어의 사용이나 사용 불능으로부터 초래된 여하한 피해에 (이익 상실, 경영 중단, 또는 정보 상실을 포함하여 다른 유사한 경우까지) 대하여, 오토닉스가 그러한 피해의 가능성에 대해 정보를 받은 적이 있다 하더라도, 책임을 지지 않습니다. 몇몇 사법권은 묵시적인 보증 또는 초래되거나 부수하여 발생하는 피해에 대한 책임 면제나 제한을 금지하고 있으므로, 위의 제한은 사용자에게 적용되지 않을 수도 있습니다. 사용자는 또한 관할 사법권에 따라 다른 법적 권리를 가질 수도 있습니다.

**본 계약서의 종결.**
오토닉스는 사용자가 이 규정을 위반할 경우 아무 때라도 본 계약서를 종결할 수 있습니다. 종결과 동시에, 사용자는 본 소프트웨어를 즉시 파기하거나 또는 본 소프트웨어의 모든 복사본을 오토닉스에 반납하여야 합니다.




//서문 끝
